services:
  expense-tracker-api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: expense_tracker_api
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - central-db_default

networks:
  central-db_default:
    external: true
