# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5440/${POSTGRES_DB}

# Hibernate
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

# OpenAPI
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Expense Tracker API
quarkus.smallrye-openapi.info-version=1.0.0

# JWT
mp.jwt.issuer=expense-tracker-api
mp.jwt.verify.issuer=expense-tracker-api
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
